[package]
name = "monad-query-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
monad-query-types = { workspace = true }

alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true, features = ["rlp"] }
alloy-rlp = { workspace = true, features = ["derive"] }
bytes = { workspace = true }
num_enum = { workspace = true }
roaring = { workspace = true }
strum = { workspace = true }
zstd = { workspace = true }
